[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "#03C988"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
# cursor = "CellForeground"
cursor = "0xdb310b"
text = "CellBackground"

[colors.dim]
black = "0x14151b"
blue = "0x4d5b86"
cyan = "0x59dffc"
green = "0x1ef956"
magenta = "0xff46b0"
red = "0xff2222"
white = "0xe6e6d1"
yellow = "0xebf85b"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "#03C988"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "#070913"
foreground = "#b3bebf"
# foreground = "#8693ad"
# foreground = "#b1b1b1"
# foreground = "#dddddd"

[colors.search.focused_match]
# background = "0xffb86c"
background = "0x2b3452"
foreground = "0x44475a"

# [colors.search.footer_bar]
# background = "0x282a36"
# foreground = "0xf8f8f2"

[colors.search.matches]
background = "0x50fa7b"
foreground = "0x44475a"

[colors.selection]
background = "0x44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
